### ISSUE TITLE
Clickable Callouts

### ISSUE THREAD

**Issue by nazywamsiepawel** [robertmryan/CustomMapViewAnnotationCalloutSwift#1]
Hey there,

I used your example to get my custom callouts working. Thanks!

One issue that is blocking me from finishing the work now is ability to make them clickable. It seems that overlaying the entire thing with a button is not working nor is the MKMapView - didSelect working correctly with it.

So tl;dr - how to make the callouts clickable?

**Comment by robertmryan** [comment]
The trick is to add `hitTest` to the annotation view (`CustomAnnotationView`) to include the callout (if present). If you want to refine it, you might add a `hitTest` to the base custom callout class (`CalloutView`) to only detect taps within the bubble (i.e. the path of the callout path). Then you should be able to do whatever you want within the final callout (e.g. I added a tap gesture to the `ExampleCalloutView`).

See the [_Location and Maps Programming Guide: Creating Callouts_](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/AnnotatingMaps/AnnotatingMaps.html#//apple_ref/doc/uid/TP40009497-CH6-SW28) for more information regarding this `hitTest` stuff.

**Comment by robertmryan** [comment]
See commit https://github.com/robertmryan/CustomMapViewAnnotationCalloutSwift/commit/ad6d1e7e4446f8644cce7d5ccfecfaa6a5669f0b.

**Comment by mattgallivan** [comment]
Thanks for this. Is there any way to prevent the underlying map view from receiving the callout's tap gesture? The callout is dismissed (despite registering the tap).

**Comment by robertmryan** [comment]
It turns out that the standard callout (with a `detailAccessoryView`) achieves this behavior with a hidden button that captures taps within the callout. (It's called `_MKSmallCalloutPassthroughButton`, discovered by examining what `hitTest` returned from standard callout.)

By adding a UIButton to the `contentView` of the `CalloutView`, you can achieve the same behavior. To provide an easy hook to this, I've implemented an empty `didTouchUpInCallout`, which you can the override to captures callout taps, rather than implementing your own `UITapGestureRecognizer`, which (a) makes it easier to detect taps in your own subclasses; and (b) adopts the same behavior as the standard callout button.

See commit https://github.com/robertmryan/CustomMapViewAnnotationCalloutSwift/commit/bf82b4f08b7a9dc4c81db74e388b7c2124ccc4a7.

**Comment by mattgallivan** [comment]
Thanks very much Robert!

**Comment by mattgallivan** [comment]
This works well when adding UILabels and UIButtons directly to the content view (ie. `contentView.addSubview(UILabel(...)))`. However, when I wrap these components in another view (eg. `UIView` or `UIStackView`) it seems to revert to its old behaviour, ignoring the catch-all `UIButton`, and dismissing the callout.

Specifically,

```
let label = UILabel()
label.text = "Test Label Should Not Close Callout"
let insideView = UIView()
insideView.addSubview(label)

// Constraints using SnapKit, but idea is the same.
label.makeConstraints { (make) -> Void in
    make.edges.equalToSuperview()
}
contentView.addSubview(insideView)
insideView.makeConstraints { (make) -> Void in
    make.edges.equalToSuperview()
}
```

**Comment by robertmryan** [comment]
Make sure to turn off user interaction. You want to make sure that user interaction falls through to the button. E.g. the following worked fine for me once I turned off user interaction:

```swift
private func configure() {
    translatesAutoresizingMaskIntoConstraints = false
    
    let stackView = UIStackView(arrangedSubviews: [titleLabel, subtitleLabel, detailsButton])
    stackView.alignment = .center
    stackView.axis = .vertical
    stackView.isUserInteractionEnabled = false
    stackView.translatesAutoresizingMaskIntoConstraints = false
    contentView.addSubview(stackView)
    detailsButton.addTarget(self, action: #selector(didTapDetailsButton(_:)), for: .touchUpInside)
    
    let views = ["stackView": stackView]
    let vflStrings = ["V:|[stackView]|", "H:|[stackView]|"]
    
    for vfl in vflStrings {
        contentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: vfl, metrics: nil, views: views))
    }
}
```

**Comment by mattgallivan** [comment]
Thanks, that did help. Unfortunately, I got side-tracked from this while trying to get a UITableView inside of the callout. I'm not sure if I could reproduce it at the moment but I believe there were still a few issues when nesting the table? Anyway, I'm sure disabling user interaction solves 99% of map use cases -- thanks very much, Rob.
