### ISSUE TITLE
How to perform segue upon button tap

### ISSUE THREAD

**Issue by robertmryan** [robertmryan/CustomMapViewAnnotationCalloutSwift#3]
I received this email:

<pre>
From: "Badarinath Venkatnarayansetty" 
Date: December 18, 2016 at 4:43:40 AM PST
Reply-To: b***@***.com

Hi Rob , 

This is regarding the  https://github.com/robertmryan/CustomMapViewAnnotationCalloutSwift

Custom CalloutView has "Details" button whichcalls   

func didTapDetailsButton(_ sender: UIButton) {
   print("didTapDetailsButton")
} , 

How can i navigate to new view controller once the control comes to this method.

Since ExampleCalloutView extends CalloutView which extends UIView , 

not able to use self.presenViewController to navigate to new view controller. 

Any help is really appreciated .
</pre>

**Comment by robertmryan** [comment]
You can add a closure that you'll pass along to the callout, which will do whatever the view controller needs. See [button-segue-example](https://github.com/robertmryan/CustomMapViewAnnotationCalloutSwift/tree/button-segue-example) branch.

**Comment by badrinathvm** [comment]
Thank you very much Rob , Your solution helped me a lot. Saved my day . Thanks a ton again
