### ISSUE TITLE
iOS 8 compatibility

### ISSUE THREAD

**Issue by reyanshh** [robertmryan/CustomMapViewAnnotationCalloutSwift#5]
Is there any replacement for the constraint section for iOS8 compatibility.

**Comment by robertmryan** [comment]
The constraint syntax is compatible with iOS8. Do you mean iOS versions prior to 8?

**Comment by robertmryan** [comment]
You can use whatever syntax you want to add constraints. I prefer the new API, but the old API works, too.

**Comment by robertmryan** [comment]
I've added a fork for iOS 8 illustrating the old constraint syntax. Or you can use VFL. Whatever you want. See https://github.com/robertmryan/CustomMapViewAnnotationCalloutSwift/tree/iOS-8.0.
